// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABXw9DE369Yrdbt2PCAiR0hFYFRx7m-7U',
    appId: '1:394000888276:web:d8fc0b37d9f4dff6b8a641',
    messagingSenderId: '394000888276',
    projectId: 'messenger-1f0fc',
    authDomain: 'messenger-1f0fc.firebaseapp.com',
    storageBucket: 'messenger-1f0fc.firebasestorage.app',
    measurementId: 'G-31BKG4K9DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLRbleRz-XM-pjQumoR0cX3wKAgG51w4',
    appId: '1:394000888276:android:3b2e2531e1864262b8a641',
    messagingSenderId: '394000888276',
    projectId: 'messenger-1f0fc',
    storageBucket: 'messenger-1f0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJQV_xLosHCy8tNF1F3gXZAv4D9nvk854',
    appId: '1:394000888276:ios:57b8fb1626945f6db8a641',
    messagingSenderId: '394000888276',
    projectId: 'messenger-1f0fc',
    storageBucket: 'messenger-1f0fc.firebasestorage.app',
    iosBundleId: 'com.example.pipdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJQV_xLosHCy8tNF1F3gXZAv4D9nvk854',
    appId: '1:394000888276:ios:57b8fb1626945f6db8a641',
    messagingSenderId: '394000888276',
    projectId: 'messenger-1f0fc',
    storageBucket: 'messenger-1f0fc.firebasestorage.app',
    iosBundleId: 'com.example.pipdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABXw9DE369Yrdbt2PCAiR0hFYFRx7m-7U',
    appId: '1:394000888276:web:4516ec5952d9d45db8a641',
    messagingSenderId: '394000888276',
    projectId: 'messenger-1f0fc',
    authDomain: 'messenger-1f0fc.firebaseapp.com',
    storageBucket: 'messenger-1f0fc.firebasestorage.app',
    measurementId: 'G-PE9M9T5KMW',
  );
}
